namespace server.domain.player;

public enum Job
{
    Apprentice = 1,
    Warrior = 2,
    Guardian = 3,
    Mage = 4,
    Priest = 5,
    Ranger = 6,
    OniWarrior = 7,
    SwordMaster = 8,
    Trickster = 9,
    Crusader = 10,
    FireMage = 11,
    WaterMage = 12,
    WindMage = 13,
    HighPriest = 14,
    Necromancer = 15,
    Sniper = 16,
    TrapMaster = 17,
    GrandWarrior = 18,
    GrandGuard = 19,
    GrandCaster = 20,
    GrandPriest = 21,
    GrandRanger = 22,
    Shogun = 23,
    Archmage = 24,
    GreatThief = 25,
    GreatKnight = 26,
    Bushin = 27,
    Seikaiou = 28,
    Matouou = 29,
    Shugoshin = 30
}
