import {
  getPlayerResponseSchema,
  listPlayersResponseSchema,
  createPlayerRequestSchema,
  createPlayerResponseSchema,
  updatePlayerNameRequestSchema,
  updatePlayerNameResponseSchema,
  updatePlayerImageRequestSchema,
  updatePlayerImageResponseSchema,
  updatePlayerJobRequestSchema,
  updatePlayerJobResponseSchema,
  updatePlayerEquipmentRequestSchema,
  updatePlayerEquipmentResponseSchema,
  updatePlayerMoveSetRequestSchema,
  updatePlayerMoveSetResponseSchema,
  sendPlayerGiftRequestSchema,
  sendPlayerGiftResponseSchema,
  rebirthPlayerResponseSchema,
} from '@/schema/player'
import {
  getChatRoomRequestSchema,
  getChatRoomResponseSchema,
  markChatMessagesAlertedRequestSchema,
  markChatMessagesAlertedResponseSchema,
  postChatMessageRequestSchema,
  postChatMessageResponseSchema,
} from '@/schema/chat'
import {
  createThreadReplyRequestSchema,
  createThreadReplyResponseSchema,
  createThreadRequestSchema,
  createThreadResponseSchema,
  deleteThreadResponseSchema,
  getThreadAlertsResponseSchema,
  getThreadsRequestSchema,
  getThreadsResponseSchema,
  markThreadRepliesAlertedRequestSchema,
  markThreadRepliesAlertedResponseSchema,
  threadDetailSchema,
} from '@/schema/thread'
import {
  getTrainingEnemiesResponseSchema,
  executeTrainingRequestSchema,
  executeTrainingResponseSchema,
} from '@/schema/training'
import {
  getQuestStagesResponseSchema,
  createQuestRoomRequestSchema,
  updateQuestRoomRestrictionsRequestSchema,
  questRoomDetailResponseSchema,
  listQuestRoomsRequestSchema,
  listQuestRoomsResponseSchema,
  updateQuestRoomPositionRequestSchema,
  questRunDetailResponseSchema,
  submitQuestCommandRequestSchema,
  submitQuestCommandResponseSchema,
  manualControlRequestSchema,
  manualControlResponseSchema,
  postQuestChatMessageRequestSchema,
  postQuestChatMessageResponseSchema,
  questRunHubSnapshotEventSchema,
  questRunHubUpdatedEventSchema,
  questRunHubErrorEventSchema,
} from '@/schema/quest'
import {
  getItemsResponseSchema,
  useItemRequestSchema,
  itemActionResponseSchema,
  synthesizeEquipmentResponseSchema,
  createMarketListingRequestSchema,
  createMarketListingResponseSchema,
  getMarketListingsResponseSchema,
  purchaseMarketListingRequestSchema,
  purchaseMarketListingResponseSchema,
} from '@/schema/item'
import {
  claimTreasureMapRewardResponseSchema,
  getCurrentTreasureMapExpeditionResponseSchema,
  getTreasureMapsResponseSchema,
  startTreasureMapExpeditionRequestSchema,
  treasureMapExpeditionSchema,
} from '@/schema/treasureMap'
import { getRankingsResponseSchema } from '@/schema/ranking'

export type {
  GetPlayerResponse,
  PlayerSummary,
  ListPlayersResponse,
  PlayerMoveSlot,
  CreatePlayerRequest,
  CreatePlayerResponse,
  UpdatePlayerNameRequest,
  UpdatePlayerNameResponse,
  UpdatePlayerImageRequest,
  UpdatePlayerImageResponse,
  UpdatePlayerJobRequest,
  UpdatePlayerJobResponse,
  UpdatePlayerEquipmentRequest,
  UpdatePlayerEquipmentResponse,
  UpdatePlayerMoveSetRequest,
  UpdatePlayerMoveSetResponse,
  SendPlayerGiftRequest,
  SendPlayerGiftResponse,
  RebirthPlayerResponse,
} from '@/schema/player'
export type {
  GetChatRoomRequest,
  GetChatRoomResponse,
  MarkChatMessagesAlertedRequest,
  MarkChatMessagesAlertedResponse,
  PostChatMessageRequest,
  PostChatMessageResponse,
} from '@/schema/chat'
export type {
  ThreadSummary,
  ThreadReply,
  ThreadDetail,
  ThreadAlertSummary,
  GetThreadsRequest,
  GetThreadsResponse,
  GetThreadAlertsResponse,
  MarkThreadRepliesAlertedRequest,
  MarkThreadRepliesAlertedResponse,
  CreateThreadRequest,
  CreateThreadResponse,
  CreateThreadReplyRequest,
  CreateThreadReplyResponse,
  DeleteThreadResponse,
} from '@/schema/thread'
export type {
  TrainingEnemy,
  GetTrainingEnemiesResponse,
  ExecuteTrainingRequest,
  ExecuteTrainingResponse,
  TrainingCooldownError,
} from '@/schema/training'
export type {
  GetQuestStagesResponse,
  CreateQuestRoomRequest,
  UpdateQuestRoomRestrictionsRequest,
  QuestRoomDetailResponse,
  ListQuestRoomsRequest,
  QuestRoomSummaryResponse,
  ListQuestRoomsResponse,
  QuestRunDetailResponse,
  SubmitQuestCommandRequest,
  SubmitQuestCommandResponse,
  ManualControlRequest,
  ManualControlResponse,
  PostQuestChatMessageRequest,
  PostQuestChatMessageResponse,
  QuestRunHubSnapshotEvent,
  QuestRunHubUpdatedEvent,
  QuestRunHubErrorEvent,
} from '@/schema/quest'
export type {
  ItemEquipmentView,
  ItemStackView,
  InventoryItemView,
  GetItemsResponse,
  UseItemRequest,
  ItemActionResponse,
  SynthesizeEquipmentResponse,
  CreateMarketListingRequest,
  CreateMarketListingResponse,
  MarketListingView,
  GetMarketListingsResponse,
  PurchaseMarketListingRequest,
  PurchaseMarketListingResponse,
} from '@/schema/item'
export type {
  ClaimTreasureMapRewardResponse,
  GetCurrentTreasureMapExpeditionResponse,
  GetTreasureMapsResponse,
  StartTreasureMapExpeditionRequest,
  TreasureMapExpedition,
  TreasureMapSummary,
} from '@/schema/treasureMap'
export type { GetRankingsResponse, RankingRow } from '@/schema/ranking'

export const endpoints = {
  player: {
    get: {
      path: '/player',
      method: 'GET',
      responseSchema: getPlayerResponseSchema,
    },
    getById: {
      path: (playerId: string) => `/players/${playerId}`,
      method: 'GET',
      responseSchema: getPlayerResponseSchema,
    },
    list: {
      path: '/players',
      method: 'GET',
      responseSchema: listPlayersResponseSchema,
    },
    create: {
      path: '/player',
      method: 'POST',
      requestSchema: createPlayerRequestSchema,
      responseSchema: createPlayerResponseSchema,
    },
    updateName: {
      path: '/player/name',
      method: 'PUT',
      requestSchema: updatePlayerNameRequestSchema,
      responseSchema: updatePlayerNameResponseSchema,
    },
    updateImage: {
      path: '/player/image',
      method: 'PUT',
      requestSchema: updatePlayerImageRequestSchema,
      responseSchema: updatePlayerImageResponseSchema,
    },
    updateJob: {
      path: '/player/job',
      method: 'PUT',
      requestSchema: updatePlayerJobRequestSchema,
      responseSchema: updatePlayerJobResponseSchema,
    },
    updateEquipment: {
      path: '/player/equipment',
      method: 'PUT',
      requestSchema: updatePlayerEquipmentRequestSchema,
      responseSchema: updatePlayerEquipmentResponseSchema,
    },
    updateMoveSet: {
      path: '/player/move-set',
      method: 'PUT',
      requestSchema: updatePlayerMoveSetRequestSchema,
      responseSchema: updatePlayerMoveSetResponseSchema,
    },
    sendGift: {
      path: (playerId: string) => `/players/${playerId}/gifts`,
      method: 'POST',
      requestSchema: sendPlayerGiftRequestSchema,
      responseSchema: sendPlayerGiftResponseSchema,
    },
    rebirth: {
      path: '/player/rebirth',
      method: 'POST',
      responseSchema: rebirthPlayerResponseSchema,
    },
  },
  chatRoom: {
    get: {
      path: '/chat/room',
      method: 'GET',
      requestSchema: getChatRoomRequestSchema,
      responseSchema: getChatRoomResponseSchema,
    },
    postMessage: {
      path: '/chat/room/messages',
      method: 'POST',
      requestSchema: postChatMessageRequestSchema,
      responseSchema: postChatMessageResponseSchema,
    },
    markAlerts: {
      path: '/chat/room/messages/alerts',
      method: 'POST',
      requestSchema: markChatMessagesAlertedRequestSchema,
      responseSchema: markChatMessagesAlertedResponseSchema,
    },
  },
  thread: {
    list: {
      path: '/threads',
      method: 'GET',
      requestSchema: getThreadsRequestSchema,
      responseSchema: getThreadsResponseSchema,
    },
    get: {
      path: (threadId: string) => `/threads/${threadId}`,
      method: 'GET',
      responseSchema: threadDetailSchema,
    },
    create: {
      path: '/threads',
      method: 'POST',
      requestSchema: createThreadRequestSchema,
      responseSchema: createThreadResponseSchema,
    },
    reply: {
      path: (threadId: string) => `/threads/${threadId}/replies`,
      method: 'POST',
      requestSchema: createThreadReplyRequestSchema,
      responseSchema: createThreadReplyResponseSchema,
    },
    delete: {
      path: (threadId: string) => `/threads/${threadId}`,
      method: 'DELETE',
      responseSchema: deleteThreadResponseSchema,
    },
    alerts: {
      path: '/threads/alerts',
      method: 'GET',
      responseSchema: getThreadAlertsResponseSchema,
    },
    markAlerts: {
      path: '/threads/alerts',
      method: 'POST',
      requestSchema: markThreadRepliesAlertedRequestSchema,
      responseSchema: markThreadRepliesAlertedResponseSchema,
    },
  },
  training: {
    getEnemies: {
      path: '/training/enemies',
      method: 'GET',
      responseSchema: getTrainingEnemiesResponseSchema,
    },
    execute: {
      path: '/training/execute',
      method: 'POST',
      requestSchema: executeTrainingRequestSchema,
      responseSchema: executeTrainingResponseSchema,
    },
  },
  quest: {
    getStages: {
      path: '/quest/stages',
      method: 'GET',
      responseSchema: getQuestStagesResponseSchema,
    },
    createRoom: {
      path: '/quest/rooms',
      method: 'POST',
      requestSchema: createQuestRoomRequestSchema,
      responseSchema: questRoomDetailResponseSchema,
    },
    listRooms: {
      path: '/quest/rooms',
      method: 'GET',
      requestSchema: listQuestRoomsRequestSchema,
      responseSchema: listQuestRoomsResponseSchema,
    },
    getRoom: {
      path: (roomId: string) => `/quest/rooms/${roomId}`,
      method: 'GET',
      responseSchema: questRoomDetailResponseSchema,
    },
    getRoomRun: {
      path: (roomId: string) => `/quest/rooms/${roomId}/run`,
      method: 'GET',
      responseSchema: questRunDetailResponseSchema,
    },
    joinRoom: {
      path: (roomId: string) => `/quest/rooms/${roomId}/join`,
      method: 'POST',
      responseSchema: questRoomDetailResponseSchema,
    },
    updateRoomPosition: {
      path: (roomId: string) => `/quest/rooms/${roomId}/positions`,
      method: 'PUT',
      requestSchema: updateQuestRoomPositionRequestSchema,
      responseSchema: questRoomDetailResponseSchema,
    },
    updateRoomRestrictions: {
      path: (roomId: string) => `/quest/rooms/${roomId}/restrictions`,
      method: 'PUT',
      requestSchema: updateQuestRoomRestrictionsRequestSchema,
      responseSchema: questRoomDetailResponseSchema,
    },
    startRoom: {
      path: (roomId: string) => `/quest/rooms/${roomId}/start`,
      method: 'POST',
      responseSchema: questRunDetailResponseSchema,
    },
    cancelRoom: {
      path: (roomId: string) => `/quest/rooms/${roomId}/cancel`,
      method: 'POST',
      responseSchema: questRoomDetailResponseSchema,
    },
    getRun: {
      path: (runId: string) => `/quest/runs/${runId}`,
      method: 'GET',
      responseSchema: questRunDetailResponseSchema,
    },
    getActiveRun: {
      path: '/quest/runs/active',
      method: 'GET',
      responseSchema: questRunDetailResponseSchema,
    },
    escapeRun: {
      path: (runId: string) => `/quest/runs/${runId}/escape`,
      method: 'POST',
      responseSchema: questRunDetailResponseSchema,
    },
    submitCommand: {
      path: (runId: string) => `/quest/runs/${runId}/commands`,
      method: 'POST',
      requestSchema: submitQuestCommandRequestSchema,
      responseSchema: submitQuestCommandResponseSchema,
    },
    requestManualControl: {
      path: (runId: string) => `/quest/runs/${runId}/manual-control/request`,
      method: 'POST',
      requestSchema: manualControlRequestSchema,
      responseSchema: manualControlResponseSchema,
    },
    approveManualControl: {
      path: (runId: string) => `/quest/runs/${runId}/manual-control/approve`,
      method: 'POST',
      requestSchema: manualControlRequestSchema,
      responseSchema: manualControlResponseSchema,
    },
    postChatMessage: {
      path: (runId: string) => `/quest/runs/${runId}/chat`,
      method: 'POST',
      requestSchema: postQuestChatMessageRequestSchema,
      responseSchema: postQuestChatMessageResponseSchema,
    },
    hub: {
      path: '/quest-hubs/runs',
      snapshotEvent: 'QuestRunSnapshot',
      snapshotEventSchema: questRunHubSnapshotEventSchema,
      updatedEvent: 'QuestRunUpdated',
      updatedEventSchema: questRunHubUpdatedEventSchema,
      errorEvent: 'QuestRunError',
      errorEventSchema: questRunHubErrorEventSchema,
      subscribeMethod: 'SubscribeRun',
      unsubscribeMethod: 'UnsubscribeRun',
    },
  },
  items: {
    get: {
      path: '/items',
      method: 'GET',
      responseSchema: getItemsResponseSchema,
    },
    use: {
      path: (itemStackId: string) => `/items/${itemStackId}/use`,
      method: 'POST',
      requestSchema: useItemRequestSchema,
      responseSchema: itemActionResponseSchema,
    },
    synthesize: {
      path: (playerEquipmentId: string) => `/items/equipments/${playerEquipmentId}/synthesize`,
      method: 'POST',
      responseSchema: synthesizeEquipmentResponseSchema,
    },
    deleteEquipment: {
      path: (playerEquipmentId: string) => `/items/equipments/${playerEquipmentId}`,
      method: 'DELETE',
      responseSchema: itemActionResponseSchema,
    },
    deleteStack: {
      path: (itemStackId: string) => `/items/stacks/${itemStackId}`,
      method: 'DELETE',
      requestSchema: useItemRequestSchema,
      responseSchema: itemActionResponseSchema,
    },
  },
  market: {
    createListing: {
      path: '/market/listings',
      method: 'POST',
      requestSchema: createMarketListingRequestSchema,
      responseSchema: createMarketListingResponseSchema,
    },
    getListings: {
      path: '/market/listings',
      method: 'GET',
      responseSchema: getMarketListingsResponseSchema,
    },
    getMyListings: {
      path: '/market/my-listings',
      method: 'GET',
      responseSchema: getMarketListingsResponseSchema,
    },
    purchase: {
      path: (listingId: string) => `/market/listings/${listingId}/purchase`,
      method: 'POST',
      requestSchema: purchaseMarketListingRequestSchema,
      responseSchema: purchaseMarketListingResponseSchema,
    },
  },
  treasureMap: {
    getMaps: {
      path: '/treasure-maps',
      method: 'GET',
      responseSchema: getTreasureMapsResponseSchema,
    },
    getCurrentExpedition: {
      path: '/treasure-map-expeditions/current',
      method: 'GET',
      responseSchema: getCurrentTreasureMapExpeditionResponseSchema,
    },
    startExpedition: {
      path: '/treasure-map-expeditions',
      method: 'POST',
      requestSchema: startTreasureMapExpeditionRequestSchema,
      responseSchema: treasureMapExpeditionSchema,
    },
    claimReward: {
      path: (expeditionId: string) => `/treasure-map-expeditions/${expeditionId}/claim`,
      method: 'POST',
      responseSchema: claimTreasureMapRewardResponseSchema,
    },
  },
  ranking: {
    get: {
      path: '/rankings',
      method: 'GET',
      responseSchema: getRankingsResponseSchema,
    },
  },
} as const
