// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.infrastructure;

#nullable disable

namespace server.infrastructure.migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.infrastructure.chat.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer")
                        .HasColumnName("sender_type");

                    b.HasKey("OwnerId", "ChatId");

                    b.ToTable("chat_messages", "internal");
                });

            modelBuilder.Entity("server.infrastructure.chat.ChatRoomEntity", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("LastChatId")
                        .HasColumnType("integer")
                        .HasColumnName("last_chat_id");

                    b.HasKey("OwnerId");

                    b.ToTable("chat_rooms", "internal");
                });

            modelBuilder.Entity("server.infrastructure.chat.ThreadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_player_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastRepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_replied_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorPlayerId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("threads", "internal");
                });

            modelBuilder.Entity("server.infrastructure.chat.ThreadReplyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_player_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorPlayerId");

                    b.HasIndex("ThreadId");

                    b.ToTable("thread_replies", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.ItemDeletionLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ItemIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("PlayerId");

                    b.ToTable("item_delete_logs", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.MarketListingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("flavor_text");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_name");

                    b.Property<DateTimeOffset>("ListedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listed_at");

                    b.Property<Guid?>("PlayerEquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_equipment_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_quantity");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SellerId");

                    b.ToTable("market_listings", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.MarketTradeHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<string>("ItemIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.ToTable("market_trade_histories", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("gold");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_path");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<int>("Job")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("job");

                    b.Property<int>("JobExp")
                        .HasColumnType("integer")
                        .HasColumnName("job_exp");

                    b.Property<int>("JobLevel")
                        .HasColumnType("integer")
                        .HasColumnName("job_level");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Luck")
                        .HasColumnType("integer")
                        .HasColumnName("luck");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<int>("MaxMp")
                        .HasColumnType("integer")
                        .HasColumnName("max_mp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("QuestCooldownUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quest_cooldown_until");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<int>("TrainingBattleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("training_battle_count");

                    b.Property<DateTimeOffset?>("TrainingCooldownUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("training_cooldown_until");

                    b.HasKey("Id");

                    b.ToTable("players", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerEquipmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<int>("Durability")
                        .HasColumnType("integer")
                        .HasColumnName("durability");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<int>("EquipmentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_status");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type");

                    b.Property<int>("Mastery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mastery");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_equipments", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerItemStackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique();

                    b.ToTable("player_item_stacks", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerMasterJobEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Job")
                        .HasColumnType("integer")
                        .HasColumnName("job");

                    b.Property<DateTimeOffset>("MasteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mastered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PlayerId", "Job");

                    b.ToTable("player_master_jobs", "internal");
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerMoveEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int?>("MoveId1")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_1");

                    b.Property<int?>("MoveId10")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_10");

                    b.Property<int?>("MoveId2")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_2");

                    b.Property<int?>("MoveId3")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_3");

                    b.Property<int?>("MoveId4")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_4");

                    b.Property<int?>("MoveId5")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_5");

                    b.Property<int?>("MoveId6")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_6");

                    b.Property<int?>("MoveId7")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_7");

                    b.Property<int?>("MoveId8")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_8");

                    b.Property<int?>("MoveId9")
                        .HasColumnType("integer")
                        .HasColumnName("move_id_9");

                    b.HasKey("PlayerId");

                    b.ToTable("player_moves", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.room.QuestRoomAllowedPlayerEntity", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("RoomId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("quest_room_allowed_players", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.room.QuestRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CloseReason")
                        .HasColumnType("integer")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MinRequiredLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_required_level");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_player_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerPlayerId")
                        .IsUnique()
                        .HasFilter("status = 1");

                    b.ToTable("quest_rooms", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.room.QuestRoomParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BattleColumn")
                        .HasColumnType("integer")
                        .HasColumnName("battle_column");

                    b.Property<int>("BattleRow")
                        .HasColumnType("integer")
                        .HasColumnName("battle_row");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<int?>("NpcTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_template_id");

                    b.Property<int>("ParticipantStatus")
                        .HasColumnType("integer")
                        .HasColumnName("participant_status");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("integer")
                        .HasColumnName("participant_type");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "BattleRow", "BattleColumn")
                        .IsUnique();

                    b.ToTable("quest_room_participants", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestFloorTrapEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("TrapId")
                        .HasColumnType("uuid")
                        .HasColumnName("trap_id");

                    b.Property<int>("ExpiresAfterFloorNo")
                        .HasColumnType("integer")
                        .HasColumnName("expires_after_floor_no");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_triggered");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer")
                        .HasColumnName("move_id");

                    b.Property<Guid>("SourceParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_participant_id");

                    b.HasKey("RunId", "TrapId");

                    b.ToTable("quest_floor_traps", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestRewardSummaryEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int?>("EquipmentRewardId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_reward_id");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<int?>("ItemRewardId")
                        .HasColumnType("integer")
                        .HasColumnName("item_reward_id");

                    b.Property<string>("SkippedRewardPlayerIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skipped_reward_player_ids_json");

                    b.HasKey("RunId");

                    b.ToTable("quest_reward_summaries", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestRunEnemyEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("EnemyInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_instance_id");

                    b.Property<string>("ActiveEffectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_effects_json");

                    b.Property<int>("BattleColumn")
                        .HasColumnType("integer")
                        .HasColumnName("battle_column");

                    b.Property<int>("BattleRow")
                        .HasColumnType("integer")
                        .HasColumnName("battle_row");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("integer")
                        .HasColumnName("current_mp");

                    b.Property<string>("DerivedParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("derived_parameters_json");

                    b.Property<int>("EnemyDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("enemy_definition_id");

                    b.Property<int>("FloorNo")
                        .HasColumnType("integer")
                        .HasColumnName("floor_no");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead");

                    b.HasKey("RunId", "EnemyInstanceId");

                    b.ToTable("quest_run_enemies", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActionDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_deadline_at");

                    b.Property<string>("ChatMessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("chat_messages_json");

                    b.Property<int>("CurrentFloorNo")
                        .HasColumnType("integer")
                        .HasColumnName("current_floor_no");

                    b.Property<int>("CurrentTurnNo")
                        .HasColumnType("integer")
                        .HasColumnName("current_turn_no");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int?>("LastResolvedTurnNo")
                        .HasColumnType("integer")
                        .HasColumnName("last_resolved_turn_no");

                    b.Property<string>("LastTurnResultsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("last_turn_results_json");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("quest_runs", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestRunPartyMemberEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<int>("ActionMode")
                        .HasColumnType("integer")
                        .HasColumnName("action_mode");

                    b.Property<string>("ActiveEffectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_effects_json");

                    b.Property<int>("CanActFromTurn")
                        .HasColumnType("integer")
                        .HasColumnName("can_act_from_turn");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("integer")
                        .HasColumnName("current_mp");

                    b.Property<string>("DerivedParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("derived_parameters_json");

                    b.Property<bool>("HasLeftQuest")
                        .HasColumnType("boolean")
                        .HasColumnName("has_left_quest");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dead");

                    b.Property<bool>("IsManualControlRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual_control_requested");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RunId", "ParticipantId");

                    b.ToTable("quest_run_party_members", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestRunPartySnapshotEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<Guid?>("ArmorPlayerEquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("armor_player_equipment_id");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_path");

                    b.Property<int>("InitialActionMode")
                        .HasColumnType("integer")
                        .HasColumnName("initial_action_mode");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<int>("Job")
                        .HasColumnType("integer")
                        .HasColumnName("job");

                    b.Property<int>("Luck")
                        .HasColumnType("integer")
                        .HasColumnName("luck");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<int>("MaxMp")
                        .HasColumnType("integer")
                        .HasColumnName("max_mp");

                    b.Property<string>("MoveSetJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("move_set_json");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("integer")
                        .HasColumnName("participant_type");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("StartColumn")
                        .HasColumnType("integer")
                        .HasColumnName("start_column");

                    b.Property<int>("StartRow")
                        .HasColumnType("integer")
                        .HasColumnName("start_row");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<Guid?>("WeaponPlayerEquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_player_equipment_id");

                    b.HasKey("RunId", "ParticipantId");

                    b.ToTable("quest_run_party_snapshots", "internal");
                });

            modelBuilder.Entity("server.infrastructure.quest.run.QuestTurnCommandEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("TurnNo")
                        .HasColumnType("integer")
                        .HasColumnName("turn_no");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<int>("ActionKind")
                        .HasColumnType("integer")
                        .HasColumnName("action_kind");

                    b.Property<bool>("IsAutoSubmitted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_submitted");

                    b.Property<int?>("MoveId")
                        .HasColumnType("integer")
                        .HasColumnName("move_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int?>("TargetColumn")
                        .HasColumnType("integer")
                        .HasColumnName("target_column");

                    b.Property<int?>("TargetRow")
                        .HasColumnType("integer")
                        .HasColumnName("target_row");

                    b.HasKey("RunId", "TurnNo", "ParticipantId");

                    b.ToTable("quest_turn_commands", "internal");
                });

            modelBuilder.Entity("server.infrastructure.ranking.RankingEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CombatIndexRank")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("combat_index_rank");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PeriodKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_kind");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("RankPosition")
                        .HasColumnType("integer")
                        .HasColumnName("rank_position");

                    b.Property<string>("RankingType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ranking_type");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SnapshotId", "RankingType", "PeriodKind", "CombatIndexRank", "RankPosition")
                        .IsUnique();

                    b.ToTable("ranking_entries", "internal");
                });

            modelBuilder.Entity("server.infrastructure.ranking.RankingSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IntervalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("interval_hours");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotAt");

                    b.ToTable("ranking_snapshots", "internal");
                });

            modelBuilder.Entity("server.infrastructure.treasuremap.TreasureMapClaimHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid>("ExpeditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("expedition_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RewardSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reward_summary_json");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("treasure_map_claim_histories", "internal");
                });

            modelBuilder.Entity("server.infrastructure.treasuremap.TreasureMapExpeditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<bool>("RewardClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reward_claimed");

                    b.Property<string>("RewardSummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reward_summary_json");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "Status");

                    b.ToTable("treasure_map_expeditions", "internal");
                });

            modelBuilder.Entity("server.infrastructure.chat.ThreadEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("AuthorPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.chat.ThreadReplyEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("AuthorPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.infrastructure.chat.ThreadEntity", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerEquipmentEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerItemStackEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerMasterJobEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.player.PlayerMoveEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithOne()
                        .HasForeignKey("server.infrastructure.player.PlayerMoveEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.quest.room.QuestRoomAllowedPlayerEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.infrastructure.quest.room.QuestRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.infrastructure.ranking.RankingEntryEntity", b =>
                {
                    b.HasOne("server.infrastructure.player.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.infrastructure.ranking.RankingSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
